name: Compilar Cidade Futurista 2026

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Compilador Pawn 3.10.10
        run: |
          wget https://www.compilgames.net/downloads/pawn/3.10.10/pawnc-3.10.10-linux.tar.gz -O pawnc.tar.gz
          tar -xzf pawnc.tar.gz
          sudo mv pawnc-3.10.10/bin/* /usr/local/bin/
          rm -rf pawnc-3.10.10 pawnc.tar.gz

      - name: Baixar Includes open.mp
        run: |
          git clone --depth 1 https://github.com/OpenMultiPlayer/omp-lib.git omp_lib
          mkdir -p dependencies
          cp -r omp_lib/*.inc dependencies/

      - name: Compilar Gamemode
        run: |
          mkdir -p gamemodes
          pawncc gamemodes/cidade2026.pwn -i"dependencies" -o"gamemodes/cidade2026.amx" -d3 -Z+

      - name: Fazer Upload do AMX (Download disponível no GitHub)
        uses: actions/upload-artifact@v4
        with:
          name: Cidade-Futurista-2026-AMX
          path: gamemodes/cidade2026.amx
