name: Compilar Cidade Futurista 2026

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: Instalar Suporte 32-bit (Ubuntu 2026)
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y libc6:i386 libncurses6:i386 libstdc++6:i386 libtinfo6:i386
          sudo ln -s /usr/lib/i386-linux-gnu/libncurses.so.6 /usr/lib/i386-linux-gnu/libncurses.so.5
          sudo ln -s /usr/lib/i386-linux-gnu/libtinfo.so.6 /usr/lib/i386-linux-gnu/libtinfo.so.5

      - name: Baixar Compilador Pawn Zeex
        run: |
          # URL COMPLETA para evitar baixar HTML por erro
          curl -L "https://github.pawn.tar.gz"
          tar -xvzf pawn.tar.gz
          echo "$(pwd)/bin" >> $GITHUB_PATH
          chmod +x ./bin/pawncc

      - name: Baixar Includes open.mp
        run: |
          git clone --depth 1 https://github.com omp_lib
          mkdir -p include
          cp -r omp_lib/*.inc include/

      - name: Compilar Gamemode
        run: |
          mkdir -p gamemodes
          # Certifique-se que o arquivo existe em gamemodes/cidade2026.pwn
          ./bin/pawncc gamemodes/cidade2026.pwn -i"include" -o"gamemodes/cidade2026.amx" -d3 -Z+ -;+

      - name: Upload AMX
        uses: actions/upload-artifact@v4
        with:
          name: Cidade-Futurista-AMX
          path: gamemodes/cidade2026.amx
