name: Compilar Cidade Futurista 2026

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Compilador Pawn (3.10.10)
        # Usando a action oficial mantida pela comunidade open.mp
        uses: southclaws/setup-pawn@v1
        with:
          version: 3.10.10

      - name: Baixar Bibliotecas open.mp (Obrigatório)
        run: |
          # Baixa as definições oficiais para não dar erro de versão
          git clone --depth 1 https://github.com omp_lib
          mkdir -p dependencies
          cp -r omp_lib/*.inc dependencies/

      - name: Compilar Gamemode 2026
        run: |
          # Cria a pasta caso não exista
          mkdir -p gamemodes
          # Compila o código apontando para as novas bibliotecas
          pawncc gamemodes/cidade2026.pwn -i"dependencies" -o"gamemodes/cidade2026.amx" -d3 -Z+ -;+

      - name: Upload do AMX (Download disponível no GitHub)
        uses: actions/upload-artifact@v4
        with:
          name: Cidade-Futurista-2026-AMX
          path: gamemodes/cidade2026.amx
