name: Compilar Cidade Futurista 2026

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      # Imagem Docker oficial da comunidade com Pawn 3.10.10
      image: compilgames/pawn:3.10.10

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Baixar Includes open.mp
        run: |
          git clone --depth 1 https://github.com/OpenMultiPlayer/omp-lib.git omp_lib
          mkdir -p dependencies
          cp -r omp_lib/*.inc dependencies/

      - name: Compilar Gamemode
        run: |
          mkdir -p gamemodes
          # pawncc já está disponível no PATH da imagem Docker
          pawncc gamemodes/cidade2026.pwn -i"dependencies" -o"gamemodes/cidade2026.amx" -d3 -Z+

      - name: Fazer Upload do AMX (Download disponível no GitHub)
        uses: actions/upload-artifact@v4
        with:
          name: Cidade-Futurista-2026-AMX
          path: gamemodes/cidade2026.amx
