name: Compilar Cidade Futurista 2026

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Instalar Compilador Pawn
        # Esta Action configura o compilador automaticamente sem erros de tar/gzip
        uses: pwn-lang/setup-pawn@master
        with:
          pawn-version: 3.10.10

      - name: Baixar Bibliotecas open.mp
        run: |
          git clone --depth 1 https://github.com omp_lib
          mkdir -p dependencies
          cp -r omp_lib/*.inc dependencies/

      - name: Compilar Gamemode
        run: |
          # O comando 'pawncc' já está disponível no PATH por causa da action acima
          # Adicionamos -i para as dependências do open.mp
          pawncc gamemodes/cidade2026.pwn -i"dependencies" -o"gamemodes/cidade2026.amx" -d3 -Z+ -;+

      - name: Upload da Cidade 2026
        uses: actions/upload-artifact@v4
        with:
          name: Cidade-Futurista-AMX
          path: gamemodes/cidade2026.amx
